### PR TITLE
added side-bar

### PR DESCRIPTION
**Pull request by anshikaa12**
>made documentation page
>added sidebar
sidebar

### CODE REVIEW

**Comment by Prabhav-Sharma** [comment]
Looks good, you can merge it.

**Comment by SanjayJatti** [comment]
You are doing great job. Looking all fine. Go ahead.

**Comment by aryan-13** [comment]
The overall structure is good! You can merge it!

**Comment by spraveenofficial** [comment]
Looks good ✌️

**Comment by Kavita539** [comment]
Its looking good, the layout is amazing!

**Pull request merged**
