### PR TITLE
added landing page

### PR DESCRIPTION
**Pull request by anshikaa12**
> added navbar, main, and footer.
>made it responsive
>structured my folder
>used button component that I made in it.
landing_page_pixelui

### CODE REVIEW

**Review by ishapatell1 — COMMENTED** [review]
Seems good anshika! Go ahead and merge it.

**Comment by SanjayJatti** [comment]
Looking very clean and awesome Anshika! You can merge it.

**Comment by anshikaa12** [comment]
> Seems good anshika! Go ahead and merge it.

Okayy!

**Comment by anshikaa12** [comment]
> Looking very clean and awesome Anshika! You can merge it.
thanks!

**Comment by amarphule** [comment]
looks good
In the Installation section, I'm seeing the "https://u-and-i.netlify.app/" link in your version 1 and version 2. 
I think it may be different for you.

**Comment by anshikaa12** [comment]
> looks good In the Installation section, I'm seeing the "https://u-and-i.netlify.app/" link in your version 1 and version 2. I think it may be different for you.
Yes that is for sample only for now 
will change it once I create my own link!

**Comment by amarphule** [comment]
Then, it's great. You have done great job.

**Pull request merged**
